### PR TITLE
Handle coffee script properly

### PR DESCRIPTION
**Pull request by ichernev**
Compile coffee script files (to javascript) before handing them to vm.createScript.

### CODE REVIEW

**Comment by nathanmacinnes** [comment]
Hi Iskren,
Would you mind creating a test for this? You'll need to create a couple of example coffee script files for the tests to load.
Thanks,
Nathan

**Comment by jeremyruppel** [comment]
This is great, was just running into this as well. Any ETA on a new npm release? Thanks!

**Comment by nathanmacinnes** [comment]
Sorry for the delay. I've been working on restructuring the tests somewhat so that they don't rely on external files (that is, I've been doing it in what little spare time I have). I wouldn't like to put anyone off using this just because the npm release doesn't have the features they need, so I'll try to get that out in the next couple of days.

**Comment by jockster** [comment]
If I do something like this, error is thrown; "Error: ENOENT, no such file or directory '...'"

```
controller = injectr(path + "controllers/Users",
  "../models/Users: 
    findByEmail: -> null 
)
```

**Comment by nathanmacinnes** [comment]
Hi @jockster, thanks for contributing. I don't understand what you're trying to do or where it's going wrong. Can you isolate that into something simple?

**Comment by jockster** [comment]
I figured out that the error goes away if I manually end the filename with `.coffee`, so I reckon that `injectr` only looks for `.js`-files.

**Pull request merged**
